### ISSUE TITLE
networking_basic metatdata references 'README.rdoc' which doesn't exist in the cookbook

### ISSUE THREAD

**Issue by bradmontgomery** [fred/fredz_cookbooks#4]
Hi,

I found the networking_basic cookbook on Opscode's community site, but the metadata.rb file references a 'README.rdoc', but the cookbook contains a 'README.textile'.

When I run `knife cookbook upload networking_basic`, chef fails with:
`ERROR: Errno::ENOENT: No such file or directory - /Users/brad/ ... /cookbooks/networking_basic/README.rdoc`

**Comment by jeffbyrnes** [comment]
Seems like this can be closed, seeing as the pull request merged in two years ago, heh.

**Comment by bradmontgomery** [comment]
😅 10 years late is better than never, right?
